system:
    PYTHONPATH: "/home/hqs5468/hua/workspace/projects/convxai_system",
    RUN_SERVICE_DIR: "/home/huashen218/workspace/convxai_system/onvxai/services/web_service",
    PORT: 10020,
    logfilePath: "/home/huashen218/workspace/convxai_system/runners/logs/web_service"

scientific_writing:
    diversity_model_dir: "huashen218/convxai-diversity-model",
    quality_model_dir: "huashen218/convxai-quality-model"

conversational_xai:
    xai_emample_embeddings_dir:
        diversity_model: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/checkpoints/xai_example_embeddings/diversity_model_train.h5",
        quality_model: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/checkpoints/xai_example_embeddings/quality_model_train.h5",
        ACL: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/explainer/xai_example_data/embeddings/diversity_model_ACL_embeddings.h5",
        CHI: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/explainer/xai_example_data/embeddings/diversity_model_CHI_embeddings.h5",
        ICLR: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/explainer/xai_example_data/embeddings/diversity_model_ICLR_embeddings.h5"
    xai_emample_texts_dir:
        ACL: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/explainer/xai_example_data/embeddings/diversity_model_ACL_texts.h5",
        CHI: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/explainer/xai_example_data/embeddings/diversity_model_CHI_texts.h5",
        ICLR: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/explainer/xai_example_data/embeddings/diversity_model_ICLR_texts.h5"
    xai_writing_aspect_prediction: "/home/huashen218/workspace/convxai_system/checkpoints/xai_models/xai_writing_aspect_prediction",
    # nlu_question_embedding_dir: "/home/hqs5468/hua/workspace/projects/convxai/src/convxai/xai_models/data/nlu/nlu_question_embedding.h5"
